// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-FYEZn0QtjeScsptew2MvDFBs63KpCrQ',
    appId: '1:623319709136:web:11359d64c5ca2a587cf5d5',
    messagingSenderId: '623319709136',
    projectId: 'community-share-26814',
    authDomain: 'community-share-26814.firebaseapp.com',
    storageBucket: 'community-share-26814.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxFqMXUllf2FCUl4dC-ljTyyB81UFzb8',
    appId: '1:623319709136:android:fcd86c39cb8eef887cf5d5',
    messagingSenderId: '623319709136',
    projectId: 'community-share-26814',
    storageBucket: 'community-share-26814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9istqUbRe8eBKQfJVkVzlneioTMfjKQE',
    appId: '1:623319709136:ios:d08fcec9f55ec7e27cf5d5',
    messagingSenderId: '623319709136',
    projectId: 'community-share-26814',
    storageBucket: 'community-share-26814.appspot.com',
    androidClientId: '623319709136-vha5opc6nill58i0t8bde5cra5fjncri.apps.googleusercontent.com',
    iosClientId: '623319709136-29nmc7kmqdkdm716daolekr3qdeocp91.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityShare',
  );
}
